# Generated by Django 6.1.1 on 2026-09-13 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('food_feedback', 'Food Feedback'), ('delivery_feedback', 'Delivery Feedback')], default='food_feedback', max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_and_others',
            field=models.TextField(blank=True),
        ),
    ]
