# Generated by Django 6.1.1 on 2026-09-13 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidasAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('verify_patient', 'Verify Patient'), ('check_credit', 'Check Credit Eligibility'), ('post_charge', 'Post Charge'), ('refund_charge', 'Refund Charge'), ('reverse_charge', 'Reverse Charge')], max_length=32)),
                ('midas_id', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=16)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'idempotency_key'], name='midas_midas_action_5b5963_idx')],
            },
        ),
    ]
