# Generated by Django 6.1.1 on 2026-09-13 15:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('outlet_manager', 'Outlet Manager'), ('kitchen_staff', 'Kitchen Staff'), ('delivery_staff', 'Delivery Staff'), ('administrator', 'Administrator')], db_index=True, default='outlet_manager', max_length=32),
        ),
    ]
