# Generated by Django 6.1.1 on 2026-09-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['name']},
        ),
    ]
