# Generated by Django 6.1.1 on 2026-09-13 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(db_index=True, help_text='Shared identifier for all lines placed in one checkout batch')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('routed', 'Routed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_delivery_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='menu.item')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.patient')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.qrcode')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.visitor')),
            ],
        ),
    ]
